### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by rwl** [SanPen/GridCal#1]
May I suggest adding a LICENSE file to the root of this project.  This would make it clear the terms under which the code may be used.

I would recommend using the same license used by MATPOWER, PYPOWER and PYPOWER-Dynamics etc. so that they may all be used together.

https://github.com/rwl/PYPOWER/blob/master/LICENSE

**Comment by SanPen** [comment]
Done, however I still need to license all the individual files...
