### ISSUE TITLE
Reintroduce Semantic Versioning

### ISSUE THREAD

**Issue by Bengt** [SanPen/GridCal#105]
In order to upgrade GridCal reliably, one needs to be able to tell which version is greater by the version number. GridCal has used semantic version numbers for this purpose for almost a year (3.0.1 - Sep 27, 2018) now. However, GridCal 3.5 breaks this feature by dropping the patch level from the version number. Now it is unclear whether version 3.5 is larger or smaller than version (non-existent) 0.3.6. I would suggest adding the patch level back in again, maybe in a version 3.5.1.

**Comment by SanPen** [comment]
totally forgot about it!
My intention is definitely to keep 3 numbers

**Comment by Bengt** [comment]
Hi Santiago,

thanks for the quick reply! I recently ran into this kind of problem, with another library, so prefered to report it, before anyone gets similar issues with GridCal.

Regards,
Bengt

**Comment by SanPen** [comment]
Hi, 

I have just uploaded 3.5.1 to Pypi, so it should be fixed.

Best regards,
Santiago

**Comment by Bengt** [comment]
I can confirm. My project's pipeline runs fine with GridCal pinned to 3.5.1:

https://gitlab.com/pfasdr/code/main/pipelines/73348504
(Should be a private URL, so just for my future reference)

**Comment by Bengt** [comment]
Thanks for the fix!
