### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by liangdong158** [SanPen/GridCal#120]
https://github.com/SanPen/GridCal/blob/dc2e6ec13de5473d9de3fb8c8cb6484751f5d701/src/GridCal/Engine/Simulations/Topology/topology_driver.py#L136

Is this line a bug ?

**Comment by SanPen** [comment]
Hi!,

You are 100% correct!
I'll fix it right away and it will be ready in the next release.

Best regards,
Santiago
