### ISSUE TITLE
"UserWarning: Transformer types are empty" when importing 3 transformer types from DGS

### ISSUE THREAD

**Issue by Bengt** [SanPen/GridCal#13]
When importing a DGS file, I hit this warning:

https://github.com/SanPen/GridCal/blob/baec770dc97ce2d6ae7ae2b0d83ff3ba78cc5b3a/UnderDevelopment/GridCal/Engine/Importers/DGS_Parser.py#L950

However, there are more than zero (3) transformer types, as requested here:

https://github.com/SanPen/GridCal/blob/baec770dc97ce2d6ae7ae2b0d83ff3ba78cc5b3a/UnderDevelopment/GridCal/Engine/Importers/DGS_Parser.py#L861

Does this `else` block need to be indented a level less?

https://github.com/SanPen/GridCal/blob/baec770dc97ce2d6ae7ae2b0d83ff3ba78cc5b3a/UnderDevelopment/GridCal/Engine/Importers/DGS_Parser.py#L949

(Note that these embedded code snippets do not reflect the intentation levels in the actual file.)

**Comment by SanPen** [comment]
You are totally right.

Fixed it.
