### ISSUE TITLE
StateEstimation example does not run

### ISSUE THREAD

**Issue by mzy2240** [SanPen/GridCal#139]
Two issues are found regarding state estimation. First, the state estimation example does not run, which seems to be due to the change of other APIs. Second, the state estimation function seems to be incorrect. In https://github.com/SanPen/GridCal/blob/master/src/GridCal/Engine/Simulations/StateEstimation/state_estimation.py at line 373, Vm is magnitudes for all types of buses while dVm is only for PQ buses and Slack bus.

**Comment by SanPen** [comment]
Hi, 

I updated the parser, now it reads both of the files you sent.

It would be nice to be able to have a larger state estimation case to check if everything works as expected. Maybe we can work on that.

Best regards,
Santiago

**Comment by mzy2240** [comment]
Thank you! I do have some large cases, but don't have any state estimation software to verify the results. Is that what you want? I could generate some pseudo measurement batches as well. Please advise what I could help.

**Comment by SanPen** [comment]
Hi, 

Yes, that would be useful. Be aware that the amount and location of the measurements need to fulfil the observability criteria. This is mostly why I haven't tried SE for larger grids. So if you have some experience with it it would be helpful.

**Comment by mzy2240** [comment]
BTW, have you checked the second issues I mentioned?

**Comment by SanPen** [comment]
Hi!

I still believe that the line where all the voltage increments are assigned (`Vm += dVm`) is correct since we are in an overdetermined problem where we try to match the voltages as best as we can to the measurements. It may be that the amount of measurements determine this piece of code too.

However I'd like to test in larger grids some time.

Do you have reason to believe otherwise?

BR,
Santiago

**Comment by mzy2240** [comment]
Hi Santiago,

Thank you for looking into it. If I understand correctly, at line 371, the size of dVm is the number of PQ buses plus 1, but the size of Vm is the size of Ybus which is the number of all type of buses. I tested on the above 5 bus case that I shared to you, and what I did is adding measurements for all the buses. If Vm += dVm, then in this case the size of two arrays do not match. I am not sure whether adding measurements for all the buses is appropriate or not, but at least from the code I don't think npq + 1 = npq + npv + slack.

**Comment by mzy2240** [comment]
Besides, I also try to validate the result by passing the pf results as measurements and to see whether it will pass the BDD test `J = np.dot(r.T, np.dot(R_inv, r))`. But J is always too large to pass the BDD. I am wondering whether it is due to I have measurements for all the buses and those net-zero injection buses (no generation and no load) are the reason.

**Comment by SanPen** [comment]
Alright!

If you could share the measuremets for the 5-node grid I'll have a look.

**Comment by mzy2240** [comment]
Sure. Here it is.
```
P_inj = [3.948380787555101,
 -7.999977535700392,
 4.399999683540577,
 -6.5061596635932496e-06,
 -1.4067612558778269e-05]
Q_inj = [1.1427943453216685,
 -2.799987179659615,
 2.974751282899865,
 6.242047310387063e-07,
 1.9570893381241474e-06]
Vm = [1.0, 0.8337707704259578, 1.04999995, 1.0193026645563943, 0.9742891883707347] # Not necessary
```

**Comment by mzy2240** [comment]
A few more parameters:

`p_inj_idx = q_inj_idx = vm_m_idx = range(0,5)`

**Comment by SanPen** [comment]
Hi, 

I found the bug. It was really silly. The assigning of of dVm should be until the end of the vector dx. See [here](https://github.com/SanPen/GridCal/blob/devel/src/GridCal/Engine/Simulations/StateEstimation/state_estimation.py).

Also, see your example [here](https://github.com/SanPen/GridCal/blob/devel/src/research/state_estimation/5_bus_se.py)

BR,
Santiago

**Comment by mzy2240** [comment]
Haha I am glad you fix it! Thanks!
I will give more tests today to see whether I could get the BDD test to pass.

**Comment by SanPen** [comment]
Hi, I'm closing the issue but feel free to reopen it if you need to discuss further.
