### ISSUE TITLE
Overflow error

### ISSUE THREAD

**Issue by ramferan** [SanPen/GridCal#142]
I found an issue trying to reload a file saved after run the action "set schematic (x, y) from (lat, lon)"

This is the console log:
  File "D:\ReposGit\github\sanpen\GridCal\src\GridCal\Gui\GridEditorWidget\editor.py", line 168, in add_bus
    elm.setPos(self.mapToScene(QPoint(x, y)))
OverflowError

**Comment by SanPen** [comment]
resolved
