### ISSUE TITLE
Miscellaneous stuff

### ISSUE THREAD

**Issue by JosepFanals** [SanPen/GridCal#156]
Hi Santiago,

First of all, I hope everything is well.

Maybe I should open separate issues, but I just wanted to make some comments on a couple details I found in the code that may be helpful:

1. Regarding the time series simulation with reactive power limits, I am not sure on the correctness of the input. In the `power_flow_worker.py` file, I see that the solver function (`acjb.NR_LS` for instance) gets something of the form `Qmin=circuit.Qmin_bus[0, :]`. From what I have checked, I think there might be an issue on the indexing. Objects such as `Qmin_bus` have a size of `n_bus x n_time`, therefore I believe the indexing should be reversed such as `Qmin=circuit.Qmin_bus[:, 0]`. Could it be?
2. When it comes to short-circuits, I would like to know up to what point the existing solver could be improved. From what I understand, the generator class does not possess information about the subtransient nor the transient reactance. In my opinion, this could be an issue because when you simply invert the admittance matrix as `Zbus = inv(calculation_inputs.Ybus.tocsc()).toarray()`, you may run into a very poorly conditioned matrix. By this I mean that `Ybus` may not have an inverse. Imagine a simple radial system without shunt admittances and where loads are ignored during the fault. Then `Ybus` is essentially singular, and some entries in `Zbus` take extremely large values. It could very well be a mistake on my side, but I ran into a problem of this nature once. From my perspective, adding the generator reactance would make the model more realistic and fix this issue. Perhaps it is already included and I am missing something.

Unrelated to the previous comments, I must confess I have a certain interest in modeling unbalanced faults. It seems you are already working on that along with @poypoyan. At which stage are you? Why exactly is it convenient to go back to abc and solve part of the problem in the phases? In Arrillaga's book it seems working all the time in the sequences should make the calculations relatively straightforward, plus I think it is generally more accepted. Any recommendation on how to approach this is welcome, I may jump into this the following month just for fun.

As always, best regards,

Josep Fanals

**Comment by poypoyan** [comment]
Hi!

I am not practicing, but as far as I remember subtransient and transient reactance makes unbalanced short circuit modelling more accurate. I am not sure how (negative sequence component iirc?). So yeah I think it should be included.

As for my approach of going back to abc: in Gridcal, you *can* select *multiple* buses that have (balanced) short-circuit faults. I honestly do not know applications for that, as I only encountered one fault in my undergrad. Now I think converting back to abc is *the* way for any possibility of "multiple unbalanced faults" (if anyone wants that...).

As for the stage, I am quite confident on computing the fault current from the 3-phase, abc, Zbus matrix. The problem that really bugs me right now is on "adding" phase shifts in the construction of *that* 3-phase abc Zbus matrix. Phase shifts are commonly ignored in power flow it seems, but I think that it is important here.

Maybe I am overthinking right now.

I just scanned and not carefully read Arrillaga's book, but yeah I also think that this is the standard. Feel free to do this unbalanced faults modelling. I hope my code in my issue and my ideas are helpful.

Best,
Ameer

**Comment by SanPen** [comment]
Hi!

Replying to Josep:

1.  not all arrays are stored as 'n_bus x n_time', but as 'n_time x n_bus'. Why? because not doing so would require the transposition of a sparse matrix which does not come for free like dense ones. So this might be one of those. Please check with the debugger if what you're getting makes sense.

2. Yes, we should add generator reactances for the short circuit. No big deal, but needs to be done.

In earlier discussions with Ameer:

My view is that if we get the full ABC formulation, the short circuit calculation is as good as it gets, whereas with sequence components you always have to compromise. The main drawback I see in sequence components short circuit is that some devices change their topology compared to the positive sequence which is weird and in my view makes for a very cumbersome implementation. Maybe it's just a matter of getting it right. @Josep, I'd advise you to look at the Arrillaga's book and see if you can get something working from there.

@poypoyan I'd continue with the 3-phase formulation. However I don't know either how to represent phase shifts in Yabc. If you observe the 3-phase formulations for transformers (i.e. in the Arrillaga book) some values are divided by sqrt(3) to repsresent the delta-wye phase shift. Maybe it is a matter to specify there further phase shifting. Certainly I'm no expert in that so maybe some literature review is needed.

Best regards,
Santiago

**Comment by poypoyan** [comment]
Hi! I missed editing my previous comment, but I already have a solution for phase shift (of course only +/- 30 deg). I am not done "testing" it.

Once I think it is alright, I'll continue with FUBM.

**Comment by JosepFanals** [comment]
Hi Santiago,

I am afraid that the Qmin and Qmax arrays are stored as n_bus x n_time. I have debugged it with a fresh GridCal install for the IEEE 30 bus with storage file that you have, and the size of the array is 30 x 96. Thus, inside `control_q_inside_method` the Qmin and Qmax passed vectors have a size of n_time. Could you please double check it? Perhaps I am making some sort of mistake on my side. 

For the unbalanced faults, I think it is best if we follow this [article](https://ieeexplore.ieee.org/abstract/document/1490591). The paper mentions that it is more computationally efficient to solve the system in positive/negative/zero sequence. Even pandapower follows this approach for their three-phase power flow solver. The modelling of the elements could be the following:

- Lines: Z1 = Z2 and Z0 is approximately 3 Z1 (see Kothari's Modern Power System Analysis). We can assume that the line is well transposed to avoid using Carson's expressions, which makes sense considering we are dealing with transmission systems. Thanks to this, we can ignore the additional current injections described in the aforementioned paper. 
- Generators: Z1 = Z2 > Z0. The value of Z0 would be given by the manufacturer, it is meant to be specified in the input file. 
- Transformers: check the paper where the admittance matrices are listed according to the configuration, including the phase shifts. 

The modelling described above corresponds to traditional elements. It is to be seen how to treat the FUBM. I mean, we could get the abc admittance matrix from it and transform it into 012 without much trouble. This would work as long as we assume that the a priori unknown admittances of the FUBM model are found with the power flow and do not change during the short-circuit. I will keep thinking about all this.

Best regards,

Josep Fanals

**Comment by SanPen** [comment]
Hi Josep, 

About Qmin and Qmax, totally right. I'm fixing it right now on the devel branch.

About the sequence components. I'll need to wrap my head around it. In the past I've done a full ABC implementation and it does not require any change in most of the functions, just in the data compilation step. However the sequence stuff, seems to require substantial trickery, for a worse outcome. TBD...

Best regards,
Santiago

**Comment by JosepFanals** [comment]
Hi Santiago,

Alright, I think we can close the issue here. I suggest keeping the discussion alive on unbalanced faults in the already open issue.

Best regards,

Josep Fanals
