### ISSUE TITLE
XXX is not available

### ISSUE THREAD

**Issue by SS4x13** [SanPen/GridCal#159]
Hi Santiago, 

When I use the command "python -c "from GridCal.ExecuteGridCal import run; run()"" to run GridCal, there are few lines information pop out as below:

Loading GridCal...
Bentayga is not available
Newton native is not available

Eigen solver is used because MKL runtime is not found.
Alliander's PGM available
Newton Power Analytics is not available: No module named 'newtonpa'

---------------------

It is metioning something is not available, does it normal? If it's not, how should I fix it?

Sorry for disturb, I am new to python and may not describe question clearly, hope your patience is not consumed. 
Thank you!

**Comment by SanPen** [comment]
Hi!

It is perfectly normal. Those are alternative calculation engines, but none of them provide more functionality. Ussually faster of the same functionality.

Please, always ask any question you may have :D

best regards,
Santiago

**Comment by SS4x13** [comment]
Appreciate for your explain!!
