### ISSUE TITLE
Dependencies missing.

### ISSUE THREAD

**Issue by vogt31337** [SanPen/GridCal#16]
Hi,

installed the software with pip install GridCal.
Didn't start, two dependencies were missing: **pulp** and **geopy**
Please add them to your setup.py

**Comment by SanPen** [comment]
As far as I can see, only geopy is missing:
[setup.py](https://github.com/SanPen/GridCal/blob/master/UnderDevelopment/setup.py)

Sometimes it fails to install the dependencies specially under linux... I have no clue why.

Just install them manually and it'll work.
