### ISSUE TITLE
Remove `np.int` support in GridCal

### ISSUE THREAD

**Issue by rzyu45** [SanPen/GridCal#174]
After numpy 1.20.0, the `np.int` alias for built-in `int` class is deprecated. 
For example, if the GridCal and the latest numpy 1.24.3 are installed together, then the following `Attribute error` is raised:
```python
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

As a result, the latest GridCal is only compatible with numpy<1.20.0, while the [requirements.txt](https://github.com/SanPen/GridCal/blob/master/requirements.txt) specifies that numpy>=1.14.0 is required. That leads to above errors if someone uses only the python API of GridCal and hence installs GridCal in conda environment.

**Comment by SanPen** [comment]
I believe I have this figured out in devel. Will deploy it later today ;)
