### ISSUE TITLE
Sheet character limit when converting to .xlsx

### ISSUE THREAD

**Issue by JosepFanals** [SanPen/GridCal#206]
Hi Santiago,

I was just testing the conversion between a .gridcal and .xlsx, and it seems that we may have a problem with sheets whose names exceed 31 characters. As far as I know this is a hard limit of Excel and there is not much we can do (perhaps other than renaming the sheets?).

For example, the "transformer2w_contingency_factor_prof.parquet" file we have in the .gridcal compressed folder becomes "transformer2w_contingency_facto" in Excel. Notice that when performing the conversion there is this warning message:

> C:\Users\a1003\Desktop\GridCal_Optimize\venv\lib\site-packages\openpyxl\workbook\child.py:99:` UserWarning: Title is more than 31 characters. Some applications may not be able to read the file warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

Just wondering if this is something that could bother you or if we should avoid using .xlsx files as much as possible.

**Comment by SanPen** [comment]
Yes, this is a known issue.

In general Excel should not be used for file saving in favor of the .gridcal as the only complete format.

**Comment by JosepFanals** [comment]
Alright, makes sense, then we can close the issue here.
