### ISSUE TITLE
Define the scope of CGMES 2.4.15 and 3.0

### ISSUE THREAD

**Issue by SanPen** [SanPen/GridCal#239]
Agree on the subset of classes to implement for CGMES 2.4.15 and 3.0

**Comment by benceszirbik** [comment]
The meeting on 23rd of Nov 2023 wee agreed on the following scope:
- we focus on EQ, Boundary, SSH, TP, SV and GL (no DY, DL profiles)
- no schedules, measurements part of OP profile
- light DC support (without too many details), the direction to PSSE will depend on the capabilities of the RAW file, second priority
- short circuit is only CGMES -> GridCal -> CGMES, not the PSS/E part
- same logic is followed for 2.4.15 and 3.0
- higher priority for EQ which is part of Spain and close neighbors
