### ISSUE TITLE
Initial message whrn importing a grid

### ISSUE THREAD

**Issue by fernpos** [SanPen/GridCal#265]
Cuando importo una red (aunque haya sido generada en GridCal), aparecen errores varios. Es muy posible que la gente piense que algo va mal en cuanto aparezca un mensaje de error al leer la red. ¿Es relevante? Si es así ok. Si se debe seguir trabajando y no pasa nada igual genera más alarma que otra cosa

**Comment by SanPen** [comment]
Ahora ya aparecen menos historias
