### ISSUE TITLE
Cannot see in reporting numbers 0.XXX  and 1.XXXX

### ISSUE THREAD

**Issue by fernpos** [SanPen/GridCal#267]
Se ve algo como esto:
![image](https://github.com/SanPen/GridCal/assets/123936552/593168f1-5301-442f-a086-ea615d56f5c2)

**Comment by SanPen** [comment]
¿Esto que significa?

**Comment by fernpos** [comment]
Simplemente que se puedan ver más decimales cuando pone 1..... . Se come los decimales
