### ISSUE TITLE
Getting clustering to simulation

### ISSUE THREAD

**Issue by fernpos** [SanPen/GridCal#268]
Cuando he guardado un caso con un clustering hecho, y lo trato de recuperar para hacer los estudios obtengo el siguiente error:
![image](https://github.com/SanPen/GridCal/assets/123936552/ecb42cc2-6ced-44f1-b0bf-77e13f4bd2b6)
![image](https://github.com/SanPen/GridCal/assets/123936552/a0c49a45-9800-43e3-82e4-bfdf412f2f28)

**Comment by SanPen** [comment]
Fixed in 5.1.8
