### ISSUE TITLE
row, column index of 2d array Sprof_fixed are opposite

### ISSUE THREAD

**Issue by hinfsynz** [SanPen/GridCal#269]
In "stochastic_power_flow_input.py" line 44,

`self.Scdf_fixed = [CDF(Sprof_fixed[i, :]) for i in range(self.n)]`

should be

`self.Scdf_fixed = [CDF(Sprof_fixed[:, i]) for i in range(self.n)]`

**Comment by SanPen** [comment]
Fantastic catch!

It's already fixed on devel ([dexing so it is correct](https://github.com/SanPen/GridCal/commit/dc1b7e8bb7e5440b3b380efd18b09666d3f8afbc)
[dc1b7e8](https://github.com/SanPen/GridCal/commit/dc1b7e8bb7e5440b3b380efd18b09666d3f8afbc))
