### ISSUE TITLE
class ContingencyMethod doesn't exist

### ISSUE THREAD

**Issue by hinfsynz** [SanPen/GridCal#270]
Constructor of class `ContingencyAnalysisOptions` doesn't take argument `engine=ContingencyMethod.PowerFlow`. It should be `engine=ContingencyEngine.PowerFlow` because of refactorization of enumeration `ContingencyMethod` to `ContingencyEngine`. This issue might exist somewhere else

**Comment by SanPen** [comment]
Hi, thanks for reporting!

There're al lot of changes and bug fixing going on in the devel branch and we're getting close to a release.
Please see if there, the problems persist.

Best regards,
Santiago

**Comment by SanPen** [comment]
also, where did you see the mismatch?

**Comment by hinfsynz** [comment]
@SanPen, examples/contingency_analysis_run.py

**Comment by SanPen** [comment]
This should be fixed now
