### ISSUE TITLE
Problema con filtro

### ISSUE THREAD

**Issue by fernpos** [SanPen/GridCal#275]
AL crear una nueva linea denominada milinea. Quiero buscarla en la DB.
Funciona con:
 - idxobj.name like mili
No funciona con:
 - idxobj.name like miline

**Comment by SanPen** [comment]
Era un problema de regex:

como se divide por "in" miline se partía en mil-in-ea y no se detectaba que el operador es like.
Ahora es obligatorio que los operadores de los filtros estén separados por espacios

Arreglado en [1b523ef](https://github.com/SanPen/GridCal/commit/1b523ef99ea6abc3faca8fd1a8cb5e740222fadb)
