### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by SanPen** [SanPen/GridCal#300]
# Proposal

This issue proposes the re-licensing of GridCal to a more permissive license, while improving the legal coverage.

## Current license: GNU Lesser General Public License (LGPL) 

- **Type**: Weak Copyleft
- **Key Features**: Allows the software to be used in proprietary applications as long as modifications to the LGPL-covered code itself are released under LGPL. Focuses on libraries or components.

### Benefits:

- Copyleft with Flexibility: Ensures that modifications to the LGPL-covered parts of GridCal are open-source, while allowing it to be used in proprietary software. Encourages contributions back to the LGPL-licensed components.

- Integration: Suitable if GridCal is intended to be used as a library or component within larger software systems, including proprietary ones.

### Drawbacks:

- Complex Compliance: Requires that any modifications to the LGPL-covered code be open-source, which can add complexity to project management.

- No Patent Protection: Lacks explicit patent protection, which might expose users to patent claims related to the LGPL code.

### Best For:

Projects where you want to ensure that any modifications to GridCal itself are open-source while allowing it to be used in proprietary applications. Ideal if GridCal is used as a library or component rather than as a standalone application.

## Proposed license: Mozilla Public License 2.0 (MPL 2.0)

- Type: Weak Copyleft
- Key Features: Requires modifications to MPL-covered code to be open-source. Allows MPL-licensed code to be combined with proprietary code in the same project.

### Benefits

- File-Level Copyleft: Only modifications to MPL-licensed files need to be open-source. This makes it easier to integrate MPL-licensed code with proprietary code without requiring the entire project to be open-source.

- Flexibility: Allows MPL code to be used in proprietary applications, which can increase adoption and use in commercial environments.

- Clear Terms: MPL 2.0 is designed to be straightforward and business-friendly, making it easier to comply with compared to some other licenses.

### Drawbacks

- File-Level Restrictions: Modifications to MPL-covered files must be open-source, which can add complexity in mixed-license environments where only some files are MPL-licensed.

- No Patent Protection: Does not include explicit patent protection, which might expose users to patent claims related to the MPL code.

### Best For

Projects where you want to ensure that modifications to the MPL-covered files are open-source while allowing integration with proprietary code in the same project. Suitable if GridCal is part of a larger proprietary system or application.

## What other projects use:

| Software                                        | License                          |
|-------------------------------------------------|----------------------------------|
| PSAT (Power System Analysis Toolbox)            | GNU General Public License (GPL) |
| GridLAB-D                                       | Custom permissive license        |
| OpenIPSL (Open Integrated Power System Library) | BSD-3-Clause license             |
| MATPOWER                                        | BSD-3-Clause license             |
| PyPSA (Python for Power System Analysis)        | MIT license                      |
| pandapower                                      | Custom permissive license        |
| Powsybl                                         | MPL-2.0 license                  |
| Power-grid-model                                | MPL-2.0 license                  |

# Required signers

Please **respond to this issue with a comment stating if you agree that your contributions that are licensed under the LGPL be re-licensed to MPL**.

- ✅ @SanPen 
- ✅ @JosepFanals 
- ✅ @Carlos-Alegre 
- ✅ @miek770 
- ✅ @benceszirbik 
- ✅ @QuimMoya 
- ✅ @Bengt 
- ✅ @ManuelNvro 
- ✅ @JanaSoler 
- ✅ @ramferan 
- ✅ @jozsefgorcs-navitasoft 
- ✅ @jag0nzalez 
- ✅ @peterkulik-navitasoft 
- ✅ @cristinafray 
- ✅ @fernpos 
- ✅ @cggaray 
- ✅ @yasirroni 
- ✅ @leeraiyan 
- ✅ @poypoyan 
- ✅ @rzyu45 
- ✅ @jahanbani 
- ✅ @ClaudiaMachadoCervera 
- ✅ @adrisanchu 
- ✅ @RanjeetHambire 
- ✅ @eyllanesc 
- ✅ @bsanjuan

**Comment by SanPen** [comment]
My personal comment; 

In choosing MPL, more people from industry could be brought into the project since that provided a more comfortable setting than LGPL, while having a similar protection. Derivative works must retain the MPL license too and there is no restriction of the way it is included in other works since the MPL is a weak Copyleft license.

Other licenses that are not copyleft such as MIT, Apache or BSD leave the possibility that some parties make derivatives of GridCal and make it closed source which in my view would be a terrible thing.

**Comment by poypoyan** [comment]
No problem for me. Thanks!

**Comment by JosepFanals** [comment]
Fine for me as well

**Comment by miek770** [comment]
Likewise, no problem for me.

**Comment by QuimMoya** [comment]
No problem !!!

**Comment by Carlos-Alegre** [comment]
No problem for me!

**Comment by SanPen** [comment]
I agree to relicense to MPL 2.0

**Comment by yasirroni** [comment]
I agree with the changes. It make GridCal allowed to be statically included on other project.

But, it is worth noting that there will be an edge case explained in SO that user will be able to add functionality while not share the functionality itself.

> someone could take one of the main file of your project, add "import my_private_new_file", and modify your main method for example by adding "my_private_new_file.newAwesomeFeature.run()".

See here: https://softwareengineering.stackexchange.com/a/400544/405045

**Comment by BegoSanjuan** [comment]
No problem for me. Thank you!

**Comment by ClaudiaMachadoCervera** [comment]
Hi Santiago,

No problem from my side.

Regards,

Claudia Machado Cervera

*Power Systems Engineer*

eRoots Analytics

Carrer del Torrent d'en Vidalet 55 L1

Barcelona, 08024

***@***.*** ***@***.***>

www.eroots.tech
  [image: Photo]

<https://www.linkedin.com/company/eroots-analytics/>
<https://eroots.tech/>

**Comment by jozsefgorcs-navitasoft** [comment]
It's okay for me!

**Comment by eyllanesc** [comment]
It's okay for me!

**Comment by peterkulik-navitasoft** [comment]
Certainly, I agree.

**Comment by RanjeetHambire** [comment]
Its OK For me Also!

**Comment by Bengt** [comment]
Yes, relicensing to a more permissive license is fine by me. Thanks for the initiative.

**Comment by jag0nzalez** [comment]
I agree!

**Comment by cristinafray** [comment]
I agree!

**Comment by jsolerIREC** [comment]
I agree to the license change!

JanaSoler

**Comment by jahanbani** [comment]
Agreed.

**Comment by leeraiyan** [comment]
Agreed!

**Comment by ManuelNvro** [comment]
I agree!

**Comment by fernpos** [comment]
I agree!

**Comment by ramferan** [comment]
I agree!

**Comment by adrisanchu** [comment]
Agreed!

**Comment by cggaray** [comment]
Agreed!

**Comment by SanPen** [comment]
Dear all, thank you for taking the time to review and accept this proposal, and thank you very much for your contributions.
The next GridCal release will be done under the MPL license.
