### ISSUE TITLE
Adding wire to Tower

### ISSUE THREAD

**Issue by yns0671** [SanPen/GridCal#306]
I am trying to impelent your distribution grid tutorial but i cannot ad wire to tower. I do same steps as you. When i click the edit tower; wire resistance value is blank, and even if I correct it, i cant add wire to tower.
**To Reproduce**
1. Go to 'Database'
2. Click on 'Wire', add wire, change parameters of the wire, 
3. Click 'Tower', add tower, right click>edit, cannot see the wire parameters which i changed and cannot add wire to tower

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version 22H

**Additional context**

**Comment by SanPen** [comment]
Should be fixed in version 5.1.27!  
Thank you for reporting.

Please let me know if it works for you.

@ClaudiaMachadoCervera @JosepFanals

**Comment by yns0671** [comment]
It is working now! Thank you very much.
