### ISSUE TITLE
New vs Old Interface

### ISSUE THREAD

**Issue by yns0671** [SanPen/GridCal#307]
**Describe the bug**
I cant find the ‘Assign selected values to the selected time slot to the grid’ button. Sice the tutorials are old, some features are changed. I could not find how to do it. (Step 10 at the Distribution Grid tutorial)
1. Go to 'Database > Load'

**Screenshots**
![eski](https://github.com/user-attachments/assets/faad248e-2e1e-4c81-a8bb-fb301a742042)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H

**Comment by yns0671** [comment]
Also, how can we run time series powerr flow.

**Comment by SanPen** [comment]
Hi, There are some UI changes indeed...

To run any simulation in time series mode, you need to active the time series mode with this button:
![imagen](https://github.com/user-attachments/assets/ee212acd-6d41-444e-bbcf-472c1c4af5fc)

The button to assign the time series step to the snapshot is located in Database:
![imagen](https://github.com/user-attachments/assets/d307dedf-42d8-4d41-9b82-d07ce8461c1b)

I hope it helps!
