### ISSUE TITLE
Fallo en el guardado de los archivos

### ISSUE THREAD

**Issue by fernpos** [SanPen/GridCal#309]
si modifico los perfiles de un caso (por ejemplo el rate o el active)
al guardar no se guardan dichos cambios:

situacion inicial:
<img width="357" alt="image" src="https://github.com/user-attachments/assets/95adfc18-4c7d-436c-a5a8-ae1159e111ae">

modifico y guardo lo siguiente:
<img width="363" alt="image" src="https://github.com/user-attachments/assets/1b474b4e-c53b-4310-8832-1a35d33f455b">

cargo el caso guardado:
<img width="343" alt="image" src="https://github.com/user-attachments/assets/3035a28e-d9c4-4fb8-a2bf-d366a99e2bc7">

**Comment by SanPen** [comment]
Fixed in 5.1.30
