### ISSUE TITLE
Can not load template values for lines

### ISSUE THREAD

**Issue by yns0671** [SanPen/GridCal#310]
**Describe the bug**
When I click on tower and change its name on edit menu, after i click accept and close edit menu, i see that its name did not change. Moreover, when i try to load this tower as template value for the lines, i cant see the created tower. I cannot load template for lines.

**Screenshots**
![bug1](https://github.com/user-attachments/assets/57abd16a-0c1c-4a6f-a7ed-98b7fe03231b)
![bug2](https://github.com/user-attachments/assets/0767df72-1fc1-4794-abb1-1cac0c9d1587)
![bug3](https://github.com/user-attachments/assets/f99258d2-82f6-44e0-8857-aea1dca15d18)
![bug4](https://github.com/user-attachments/assets/a61e6fdc-d14c-439b-83f1-d2ffe809e0ae)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H

**Comment by yns0671** [comment]
Also, can we change scale on diagram from megawatt to kilowatt for example?

**Comment by SanPen** [comment]
> Also, can we change scale on diagram from megawatt to kilowatt for example?

In general not. This may be done in the future but it is quite a lot of work to change everything to display only the power values / 1000...

**Comment by yns0671** [comment]
I can see the tower on the associations of the line, but I cannot add the parameters of the tower to the lines on the diagram.
Also, i cannnot load template values when i double click on the lines at the diagram.
![2](https://github.com/user-attachments/assets/c81adf97-847c-434e-92c3-819362c58a2b)

**Comment by SanPen** [comment]
What is the `Vnom` of the tower?
What is the `Vnom` of the buses where the line is connected?
Those values should be within 10% difference, and ideally the same.

**Comment by yns0671** [comment]
thanks for the clarification. I can do this on the diagram one by one . How can i load the template values for all lines at once on the database?

**Comment by SanPen** [comment]
Do you mean, set a templates to all lines?
Your best chance is using a little scripting:

``` python
for line in app.circuit.lines:
    line.apply_template(obj=my_template, Sbase=100.0)
```

**Comment by yns0671** [comment]
thank you very much
