### ISSUE TITLE
Per  Unit usceptance

### ISSUE THREAD

**Issue by yns0671** [SanPen/GridCal#311]
**Describe the bug**
![line](https://github.com/user-attachments/assets/174113af-320f-415b-abc4-ea322cfa7095)
I try to use these values for lines. When I enter Ohm values for resistances and reactances it calculates per unit values automatically, or vice versa. However,it works wrong for susceptance. For example, it should give 0.158 per unit but it gives -158007010000.000000 per unit. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H

**Comment by emadellaloggia** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by SanPen** [comment]
??

**Comment by SanPen** [comment]
If you double click on a line you can enter values in per-unit.
It is necessary that you have the line buses voltage properly set

**Comment by yns0671** [comment]
When i enter per unit values, this time susceptance value is changed for example from 395 to 0.000395. it may be a problem with units.

**Comment by SanPen** [comment]
what are the bus voltages?

**Comment by yns0671** [comment]
230 kV

**Comment by SanPen** [comment]
Fixed it and unified with a function of the lines called `fill_design_parameters`.
Should be fine in 5.1.37
