### ISSUE TITLE
Map Diagram Issue: Substation Circles

### ISSUE THREAD

**Issue by yns0671** [SanPen/GridCal#322]
**Is your feature request related to a problem? Please describe.**
Recently, I noticed a regression in the map diagram rendering in GridCal. Previously, the map diagram was clearer and easier to interpret. However, after the latest updates, adding substations results in the drawing of oversized circles, making the diagram less readable and cluttered.

**Describe the solution you'd like**
As before, whe should be able to add substations as lines similar to the ones in the branch diagram. 

**Additional context**

![Capture](https://github.com/user-attachments/assets/8092ca64-9325-4f46-93ff-84a31f1134da)

**Comment by SanPen** [comment]
Hi, In the diagram settings you should be able to adjust the nodes sizes by changing the `node min size` parameter. That is going to be linked to the diagram after that. Let me know if it works for you.

**Comment by yns0671** [comment]
it worked. thanks
