### ISSUE TITLE
Undocumented problem with OpfDriver.py?

### ISSUE THREAD

**Issue by miek770** [SanPen/GridCal#55]
Hi Santiago,

Is there an issue with `OpfDriver`? I noticed it was commented out from `GridCalMain.py`, leading to the following error when invoked from the GUI:

```
Traceback (most recent call last):
  File "C:\Users\michel\gits\windfarm\GridCal\UnderDevelopment\GridCal\Gui\Main\GridCalMain.py", line 2498, in run_opf
    self.optimal_power_flow = OptimalPowerFlow(self.circuit, options)
NameError: name 'OptimalPowerFlow' is not defined
```

I tried removing the comment and running it on the `IEEE 30 Bus with storage.xlsx` grid and it seems to be working fine, although I didn't *really* analyze the results.

Michel

Edit: It was commented out in [this commit](https://github.com/SanPen/GridCal/commit/8422d410e93be86b17994af23fbc7a521fbc32b2), but it doesn't really say why.

**Comment by SanPen** [comment]
This was a bug due to incorrectly commenting an import
