### ISSUE TITLE
Read the docs

### ISSUE THREAD

**Issue by miek770** [SanPen/GridCal#62]
Hi Santiago,

So the new documentation is pretty much ready to go, I'd like to have your input before doing the PR. Could you please check it out here: [https://gridcal-wip.readthedocs.io/](https://gridcal-wip.readthedocs.io/)?

Please note that I've adapter the README.md accordingly, see here: [https://github.com/miek770/GridCal/blob/doc/README.md](https://github.com/miek770/GridCal/blob/doc/README.md). I've also added a basic contribution guide here: [https://gridcal-wip.readthedocs.io/development.html#contributing](https://gridcal-wip.readthedocs.io/development.html#contributing), following #60.

Next steps:

- Remove the GitHub wiki, and integrate its information to Read the Docs (RTD);
- Expand autodoc's coverage to additional modules/classes (reformat docstrings accordingly);
- ~~Integrate the HVDC manual~~;
- Remove GridCal's PDF manual from the repo;
- ~~Activate PDF generation on RTD~~;
- Document the different types of analysis and their respective options.

Let me know what you think!

Michel

2019-02-07: Added item; crossed item.

**Comment by andreas1024** [comment]
Hi, I just read through your "Newton-Raphson-Iwamoto" page - looks quite good - however, I noticed some missing line breaks between equations and I might be wrong, but I think the two derivatives of S near the bottom have their right sides interchanged.

**Comment by miek770** [comment]
Thanks @andreas1024, I've created PR #66 for the missing line breaks. I'll update the docs once it's merged (having some issues with RTD builds failing unless i manually wipe the previous build each time).

@SanPen: Any thoughts on the other issue (about the 2 derivatives of S)?
